---
- name: Install packages for Rails env
  hosts: app
  vars:
    ruby_version: 2.3.3
    root_user: root
    rbenv_root: /usr/local/rbenv
  tasks:
    #
    # Install rbenv and Ruby
    #
    - name: Install dependencies for rbenv
      apt: name={{ item }} state=present
      with_items:
        - git
      become: True
    - name: Install rbenv
      become: True
      become_user: "{{ root_user }}"
      apt: name={{ item }}
      with_items:
        - rbenv
    - name: Install dependencies for ruby-build
      become: True
      apt: name={{ item }} state=present
      with_items:
        - gcc
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
    - name: Install ruby-build as rbenv plugin
      become: True
      become_user: "{{ root_user }}"
      git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
    - name: Check Ruby already installed
      shell: which ruby
      register: ruby_install
      failed_when: ruby_install.rc not in [0, 1]
    - name: Add $PATH to ~/.bashrc
      shell: "{{ item.cmd }}"
      with_items:
        - cmd: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        - cmd: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      failed_when: ruby_install.rc == 1
    - name: Install Ruby version "{{ ruby_version }}"
      command: 'rbenv install "{{ ruby_version }}"'
      failed_when: ruby_install.rc == 1
    - name: Execute rbenv rehash
      command: rbenv rehash
    - name: Change global Ruby version
      command: 'rbenv global "{{ ruby_version }}"'
    - name: Execute rbenv rehash
      command: rbenv rehash
      #failed_when: ruby_install.rc == 1
    #
    # Install for node.js
    #
    - name: Check nodejs already installed
      shell: which nodejs
      register: nodejs_installed
      failed_when: nodejs_installed.rc not in [0, 1]
    - name: Update apt-get
      become: True
      apt: update_cache=yes
      failed_when: nodejs_installed.rc == 1
    - name: Install Nodejs
      become: True
      apt: name=nodejs state=present
      failed_when: nodejs_installed.rc == 1
    - name: Install npm
      become: True
      apt: name=npm state=present
      failed_when: nodejs_installed.rc == 1
