---
- name: Install packages for MySQL Database
  hosts: db
  vars:
    mysql_version: 5.6
    mysql_user: root
    mysql_password: root
    mysql_database: ansible_test_database
  tasks:
    #
    # Install MySQL
    #
    - name: Update apt-get
      become: True
      apt: update_cache=yes
    - name: Install mysql
      apt: name={{ item }} state=latest
      become: True
      become_user: "{{ mysql_user }}"
      with_items:
        - mysql-server-{{ mysql_version }}
        - python-mysqldb
        #- libmysqld-dev
        #- libmysqlclient-dev
    - name: Set mysql service to start on boot
      become: True
      become_user: "{{ mysql_user }}"
      service: name=mysql state=started enabled=true
    - name: Put develop.cnf
      become: True
      become_user: "{{ mysql_user }}"
      template: src=templates/develop.cnf.j2 dest=/etc/mysql/conf.d/develop.cnf backup=true mode=0644
    - name: Set the root privileges
      mysql_user:
        user: root
        host: "{{ item }}"
        password: "{{ mysql_password }}"
        with_items:
          - "%"
          - 127.0.0.1
          - ::1
          - localhost
    #    - name: Create mysql database
    #      become: True
    #      become_user: "{{ mysql_user }}"
    #      mysql_db: name={{ mysql_database }} state=present
    #    - name: Create mysql user
    #      become: True
    #      become_user: "{{ mysql_user }}"
    #      mysql_user: name={{ mysql_user }} host={{ item }} password={{ mysql_password }} priv={{ mysql_database }}.*:ALL,GRANT state=present
    #      with_items:
    #        - localhost
    #        - 127.0.0.1.%
    #    - name: uncomment a line bind-address = 127.0.0.1
    #      replace: >
    #        dest=/etc/mysql/mysql.conf.d/mysql.cnf
    #        regexp='^bind-address'
    #        replace='#bind-address'
    #    - name: Start mysql server
    #      become: True
    #      become_user: "{{ mysql_user }}"
    #      service: name=mysql state=restarted enabled=yes
