VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true

  config.vm.define "app" do |vagrant|
    vagrant.vm.box = "ubuntu/xenial64"
    vagrant.vm.hostname = "app"
    vagrant.vm.network "private_network", ip: "192.168.33.11", auto_config: false
    vagrant.vm.network :forwarded_port, guest: 80, host: 8080
    vagrant.vm.network :forwarded_port, guest: 433, host: 8443
    vagrant.vm.provision 'shell', inline: "ifconfig enp0s8 192.168.33.11"
    vagrant.vm.provision 'shell', inline: "sed -i 's/exit\ 0/ifconfig\ enp0s8\ 192\.168\.33\.11/g' /etc/rc.local"
    vagrant.vm.provision 'shell', inline: "echo 'exit 0' >> /etc/rc.local"
    vagrant.vm.provision 'shell', inline: "chmod 644 /vagrant/.ssh/authorized_keys"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "application.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = "app"
  end

end
