VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true

  config.vm.define "app" do |vagrant|
    vagrant.vm.box = "ubuntu/xenial64"
    vagrant.vm.network "private_network", ip: "192.168.33.11"
    vagrant.vm.network :forwarded_port, guest: 3000, host: 3000
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  $is_windows = RbConfig::CONFIG['host_os'] =~ /mswin|msys|mingw|cygwin|bccwin/i
  $is_osx = RbConfig::CONFIG['host_os'] =~ /darwin/i

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "application.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = "all"
  end

end
